[package]
name = "damus"
version = "0.1.0"
authors = ["William Casarin <jb55@jb55.com>"]
edition = "2021"
#rust-version = "1.60"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
#egui-android = { git = "https://github.com/jb55/egui-android.git" }  
egui = "0.20.0"
eframe = { version = "0.20.0", features = [ "wgpu" ] }
#eframe = "0.20.0"
egui_extras = { version = "0.20.0", features = ["image", "svg"] }
ehttp = "0.2.0"
image = { version = "0.24", features = ["jpeg", "png", "webp"] }
log = "0.4.17"
poll-promise = "0.2.0"
serde_derive = "1"
serde = { version = "1", features = ["derive"] } # You only need this if you want app persistence
tracing = "0.1.37"
tracing-subscriber = "0.3"
ewebsock = "0.2.0"
#wasm-bindgen = "0.2.83"
wasm-bindgen-futures = "0.4"


# web:
[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.6"
tracing-wasm = "0.2"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.11.1"
#android-activity = "0.4.0"
#winit = "0.27.5"
#winit = { version = "0.28", features = [ "android-native-activity" ] }
#winit = { git="https://github.com/rust-windowing/winit.git", rev = "2a58b785fed2a3746f7c7eebce95bce67ddfd27c", features = ["android-native-activity"] }

[package.metadata.android]
package = "com.damus.app"
apk_name = "damus"
#assets = "assets"

[[package.metadata.android.uses_feature]]
name = "android.hardware.vulkan.level"
required = true
version = 1

[[package.metadata.android.uses_permission]]
name = "android.permission.WRITE_EXTERNAL_STORAGE"
max_sdk_version = 18

[[package.metadata.android.uses_permission]]
name = "android.permission.INTERNET"

[package.metadata.android.application]
label = "Damus"
